/**
 * gen-taxonomy-sql.ts — emit the SQL projection of lib/genres/taxonomy.ts.
 *
 * The taxonomy is authored ONCE in TypeScript (GENRE_TAXONOMY.md §3.1). SQL can't
 * import it, so the primary-genre walk that the Postgres side needs (taste
 * genre_weights trigger; chart primary) is GENERATED from the same source here —
 * never hand-maintained a second time. This retires the triplicated PRECEDENCE
 * (the SQL copy) by replacing it with a data projection of the taxonomy graph:
 *
 *   _taxonomy_alias(folded PK, genre_id)          fold(id|alias) → canonical id
 *   _taxonomy_node (genre_id PK, level_rank, node_rank, display_lower)
 *   _taxonomy_closure(ancestor_id, descendant_id) self + transitive sound|scene edges
 *   _genre_resolve(text) → text                    the SQL twin of resolveGenre()
 *   _primary_genre_tag(text[]) → text              the SQL twin of primaryTagOf()
 *   _primary_genre_id(text[])  → text              the SQL twin of primaryOf()
 *
 * The closure is the id-based category-membership primitive (GENRE_TAXONOMY.md §4
 * Phase 2 task 2): "album's primary is under surface node X" == a row
 * (ancestor=X, descendant=primary_id) exists. It powers both the chart-primary
 * filter (_rg_primary_matches, hand-wired in the chart migration) and the
 * homepage category projection (lib/genres/categories.ts, via ancestorsOf).
 *
 * `fold` is byte-identical to lib/genres/resolver.ts (lower + strip non-alnum),
 * and the alias map is seeded ids-first exactly like aliasMap() there, so a raw
 * tag resolves to the same node in SQL as in TS.
 *
 * Regenerate after ANY taxonomy.ts edit and ship the emitted SQL as a migration:
 *   npx tsx scripts/gen-taxonomy-sql.ts supabase/migrations/<ts>_genre_taxonomy_sql.sql
 * With no path it prints to stdout.
 */
import { writeFileSync } from 'node:fs';
import { TAXONOMY, type GenreLevel } from '../lib/genres/taxonomy';
import { fold, ancestorsOf } from '../lib/genres/resolver';

const LEVEL_RANK: Record<GenreLevel, number> = { family: 0, genre: 1, subgenre: 2 };

/** Rebuild resolveGenre's alias map: ids first (authoritative), then aliases. */
function aliasPairs(): [string, string][] {
  const map = new Map<string, string>();
  for (const node of TAXONOMY) map.set(fold(node.id), node.id);
  for (const node of TAXONOMY) {
    for (const a of node.aliases) {
      const f = fold(a);
      if (f && !map.has(f)) map.set(f, node.id);
    }
  }
  return [...map.entries()].sort((a, b) => a[0].localeCompare(b[0]));
}

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

function main() {
  const aliases = aliasPairs();
  const nodes = [...TAXONOMY]
    .map((n) => ({
      id: n.id,
      lr: LEVEL_RANK[n.level],
      rank: n.rank,
      display: n.display.en.toLowerCase(),
    }))
    .sort((a, b) => a.id.localeCompare(b.id));

  // Transitive-closure edges (ancestor → descendant) over BOTH sound and scene
  // parents, plus the reflexive self-pair for every node — byte-identical to the
  // membership resolver.ts's ancestorsOf() drives (a node's row = itself + every
  // node whose ancestor set contains it). Sorted for a stable diff.
  const closure: [string, string][] = [];
  for (const node of TAXONOMY) {
    closure.push([node.id, node.id]); // reflexive: a surface node contains itself
    for (const anc of ancestorsOf(node.id)) closure.push([anc, node.id]);
  }
  closure.sort((a, b) => a[0].localeCompare(b[0]) || a[1].localeCompare(b[1]));

  const aliasValues = aliases.map(([f, id]) => `  (${q(f)}, ${q(id)})`).join(',\n');
  const nodeValues = nodes
    .map((n) => `  (${q(n.id)}, ${n.lr}, ${n.rank}, ${q(n.display)})`)
    .join(',\n');
  const closureValues = closure.map(([a, d]) => `  (${q(a)}, ${q(d)})`).join(',\n');

  const sql = `-- GENERATED by scripts/gen-taxonomy-sql.ts from lib/genres/taxonomy.ts — DO NOT EDIT BY HAND.
-- Regenerate after any taxonomy.ts change. See GENRE_TAXONOMY.md §3.2 / §4 Phase 2.
--
-- The SQL projection of the canonical taxonomy: the primary-genre walk the
-- Postgres side needs (taste weighting trigger; chart primary), derived from the
-- SAME source of truth as the TS resolver so a raw tag resolves identically on
-- both sides. Replaces the hand-maintained SQL PRECEDENCE (the 3rd copy).
--
-- Nodes: ${nodes.length}.  Alias/id fold keys: ${aliases.length}.  Closure edges: ${closure.length}.

BEGIN;

-- ── fold(id|alias) → canonical genre id (ids seeded first, aliases can't shadow)
CREATE TABLE IF NOT EXISTS _taxonomy_alias (
  folded   text PRIMARY KEY,
  genre_id text NOT NULL
);
TRUNCATE _taxonomy_alias;
INSERT INTO _taxonomy_alias (folded, genre_id) VALUES
${aliasValues};

-- ── per-node attributes for the primary walk + chart display projection
CREATE TABLE IF NOT EXISTS _taxonomy_node (
  genre_id      text PRIMARY KEY,
  level_rank    int  NOT NULL,   -- family 0 < genre 1 < subgenre 2 (specificity)
  node_rank     int  NOT NULL,   -- tie-break within a level (higher = more specific)
  display_lower text NOT NULL    -- lower(display.en); chart primary string
);
TRUNCATE _taxonomy_node;
INSERT INTO _taxonomy_node (genre_id, level_rank, node_rank, display_lower) VALUES
${nodeValues};

-- ── id-based category membership: (ancestor, descendant) over sound+scene edges,
-- reflexive. Row (X, P) ⟺ primary id P is "under" surface node X. The SQL twin of
-- resolver.ts ancestorsOf() (∪ self). Powers _rg_primary_matches (chart primary).
CREATE TABLE IF NOT EXISTS _taxonomy_closure (
  ancestor_id   text NOT NULL,
  descendant_id text NOT NULL,
  PRIMARY KEY (ancestor_id, descendant_id)
);
TRUNCATE _taxonomy_closure;
INSERT INTO _taxonomy_closure (ancestor_id, descendant_id) VALUES
${closureValues};

-- ── fold: byte-identical to lib/genres/resolver.ts fold() (lower + strip non-alnum)
CREATE OR REPLACE FUNCTION _genre_fold(p_tag text)
RETURNS text LANGUAGE sql IMMUTABLE AS $$
  SELECT regexp_replace(lower(coalesce(p_tag, '')), '[^a-z0-9]', '', 'g');
$$;

-- ── resolveGenre(rawTag) → canonical genre id | NULL
CREATE OR REPLACE FUNCTION _genre_resolve(p_tag text)
RETURNS text LANGUAGE sql STABLE AS $$
  SELECT a.genre_id FROM _taxonomy_alias a WHERE a.folded = _genre_fold(p_tag);
$$;

-- ── primaryTagOf(genres[]) → the RAW array element that is the album's primary
-- genre (most-specific resolvable node: level, then rank, then array order), or
-- the first tag when nothing resolves. Returns the raw tag (NOT the id): taste
-- weighting keys genre_weights on raw tags and iOS reads those keys.
CREATE OR REPLACE FUNCTION _primary_genre_tag(p_genres text[])
RETURNS text LANGUAGE sql STABLE AS $$
  WITH g AS (
    SELECT x AS tag, ord, _genre_resolve(x) AS gid
    FROM unnest(coalesce(p_genres, '{}'::text[])) WITH ORDINALITY AS t(x, ord)
  ),
  r AS (
    SELECT g.tag, g.ord, n.level_rank, n.node_rank
    FROM g JOIN _taxonomy_node n ON n.genre_id = g.gid
  )
  SELECT COALESCE(
    (SELECT tag FROM r ORDER BY level_rank DESC, node_rank DESC, ord ASC LIMIT 1),
    p_genres[1]
  );
$$;

-- ── primaryOf(genres[]) → the canonical NODE ID of the album's primary genre
-- (most-specific resolvable: level, then rank, then array order), or NULL when
-- NO tag resolves. Unlike _primary_genre_tag this returns the id (not the raw
-- tag) and does NOT fall back to genres[1]: the CHART primary keys on ids for
-- closure membership, and a NULL lets _rg_primary_matches degrade to whole-array
-- substring matching for the (rare) all-off-taxonomy album. See the chart migration.
CREATE OR REPLACE FUNCTION _primary_genre_id(p_genres text[])
RETURNS text LANGUAGE sql STABLE AS $$
  WITH g AS (
    SELECT _genre_resolve(x) AS gid, ord
    FROM unnest(coalesce(p_genres, '{}'::text[])) WITH ORDINALITY AS t(x, ord)
  ),
  r AS (
    SELECT g.gid, g.ord, n.level_rank, n.node_rank
    FROM g JOIN _taxonomy_node n ON n.genre_id = g.gid
  )
  SELECT gid FROM r ORDER BY level_rank DESC, node_rank DESC, ord ASC LIMIT 1;
$$;

-- NOTE: the CHART primary wiring (_compute_primary_genre → _primary_genre_id,
-- _rg_primary_matches → _taxonomy_closure membership, and the rg_primary_genre
-- backfill) lives in the hand-written chart migration that DEPENDS on this
-- projection — kept separate so the 5 chart RPCs stay untouched and the wiring
-- stays reviewable. See GENRE_TAXONOMY.md §4 Phase 2 task 2.

COMMIT;
`;

  const out = process.argv[2];
  if (out) {
    writeFileSync(out, sql);
    console.error(`wrote ${out} (${nodes.length} nodes, ${aliases.length} alias keys)`);
  } else {
    process.stdout.write(sql);
  }
}

main();
