#!/usr/bin/env node
/**
 * Pulls the app's real brand assets out of the iOS asset catalog so the mock
 * screens and marketing copy use the exact same icons and logos as the app.
 *
 *   node sync-assets.mjs     (export.mjs also runs this automatically)
 *
 * Writes:
 *   assets/sj-assets.js      window.SJ_ASSETS = { icons: { home: '<svg…>', … }, logoText: '<svg…>' }
 *   assets/logo-flower.svg   halftone flower logo (logo-flower.imageset)
 *   assets/app-icon.png      App Store icon, light (AppIcon.appiconset)
 *   assets/app-icon-dark.png App Store icon, dark
 *
 * The icon SVGs are inlined (not <img>) so they inherit `currentColor`, the
 * same way SwiftUI tints them with `.renderingMode(.template)`.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const XC = path.resolve(ROOT, '../sillajuku/Assets.xcassets');
const OUT = path.join(ROOT, 'assets');

export function syncAssets({ quiet = false } = {}) {
  if (!fs.existsSync(XC)) {
    if (!quiet) console.warn(`sync-assets: asset catalog not found at ${XC}; keeping existing assets/`);
    return false;
  }
  fs.mkdirSync(OUT, { recursive: true });

  const clean = (svg) => svg
    .replace(/<\?xml[^>]*\?>/g, '')
    .replace(/\s+id="[^"]*"/g, '')
    .replace(/\s+data-name="[^"]*"/g, '')
    .replace(/\s*\n\s*/g, ' ')
    .trim();

  const icons = {};
  for (const dir of fs.readdirSync(XC)) {
    const m = dir.match(/^icon-(.+)\.imageset$/);
    if (!m) continue;
    const svgFile = fs.readdirSync(path.join(XC, dir)).find((f) => f.endsWith('.svg'));
    if (!svgFile) continue;
    icons[m[1]] = clean(fs.readFileSync(path.join(XC, dir, svgFile), 'utf8'));
  }

  // Wordmark paths ship without a fill; give the root currentColor so it tints.
  const logoText = clean(fs.readFileSync(path.join(XC, 'logo-text.imageset/logo-text.svg'), 'utf8'))
    .replace('<svg ', '<svg fill="currentColor" ');

  fs.writeFileSync(
    path.join(OUT, 'sj-assets.js'),
    '/* Generated by sync-assets.mjs from apps/ios/sillajuku/Assets.xcassets. Do not edit. */\n'
      + `window.SJ_ASSETS = ${JSON.stringify({ icons, logoText }, null, 0)};\n`,
  );
  fs.copyFileSync(path.join(XC, 'logo-flower.imageset/logo-flower.svg'), path.join(OUT, 'logo-flower.svg'));
  fs.copyFileSync(path.join(XC, 'AppIcon.appiconset/AppIcon.png'), path.join(OUT, 'app-icon.png'));
  fs.copyFileSync(path.join(XC, 'AppIcon.appiconset/AppIcon-dark.png'), path.join(OUT, 'app-icon-dark.png'));
  if (!quiet) console.log(`sync-assets: ${Object.keys(icons).length} icons + wordmark + flower logo + app icons → assets/`);
  return true;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) syncAssets();
