export interface UserProfile {
  id: string;
  name: string;
  handle: string;
  initial: string;
  avatarColor: string;
  bio: string;
  ratings: number;
  reviews: number;
  following: number;
  followers: number;
  avgScore: number;
  distribution: number[];
  topGenres: { name: string; count: number }[];
  insights: string[];
  relationshipInsights?: string[];
  pinnedAlbumIds: (string | null)[];
  badges: string[];
}

export const userProfiles: Record<string, UserProfile> = {
  kenneth: {
    id: 'kenneth',
    name: 'Kenneth',
    handle: '@kenneth',
    initial: 'K',
    avatarColor: 'mint-bg border-mint text-mint-dark',
    bio: 'Music explorer. K-indie obsessive. Somehow still listening to 2012 K-Pop.',
    ratings: 247,
    reviews: 38,
    following: 12,
    followers: 31,
    avgScore: 3.8,
    distribution: [10, 18, 28, 36, 48, 56, 60, 72, 64, 44],
    topGenres: [
      { name: 'K-R&B', count: 64 },
      { name: 'K-Indie', count: 48 },
      { name: 'Hip-Hop', count: 38 },
      { name: 'K-Pop', count: 31 },
      { name: 'R&B', count: 22 },
    ],
    insights: [
      "Your ratings land close to the community average",
      "Perfect scores are rare for you — only 6 given",
      "You're not afraid to rate low — 26% are 2★ or below",
    ],
    pinnedAlbumIds: ['midsummer-night', 'lilac', 'palette', 'broken-mirror', 'chat-shire', 'modern-times', 'the-shower', null, null],
    badges: ['K-R&B connoisseur', 'All or nothing'],
  },
  jiyeon_music: {
    id: 'jiyeon_music',
    name: 'jiyeon_music',
    handle: '@jiyeon_music',
    initial: 'J',
    avatarColor: 'bg-rose-50 border-rose-200 text-rose-600',
    bio: 'K-indie & K-R&B obsessive. Playlist curator. Finding beauty in the quiet tracks.',
    ratings: 184,
    reviews: 52,
    following: 89,
    followers: 342,
    avgScore: 4.1,
    distribution: [6, 10, 16, 22, 32, 42, 50, 58, 62, 48],
    topGenres: [
      { name: 'K-Indie', count: 58 },
      { name: 'Jazz', count: 42 },
      { name: 'K-R&B', count: 36 },
      { name: 'Folk', count: 28 },
      { name: 'Indie Pop', count: 20 },
    ],
    insights: [
      "You rate higher than most — generous with 4★ and above",
      "K-Indie dominates 32% of your catalog",
      "You write more reviews than you rate — a storyteller",
    ],
    relationshipInsights: [
      "You both love K-R&B and K-Indie — strong taste overlap",
      "jiyeon_music rates 0.3 points higher on average than you",
      "You disagree on Get Up — they rated it 4.5, you gave 3.5",
      "They've rated 38 albums you haven't heard yet",
      "Jazz is their #2 genre but doesn't appear in your top 5",
    ],
    pinnedAlbumIds: ['broken-mirror', 'her', 'seonmul', 'japcho', 'night-swimming', 'bleu', 'realists', null, null],
    badges: ['K-Indie curator', 'Generous rater'],
  },
  minwave: {
    id: 'minwave',
    name: 'minwave',
    handle: '@minwave',
    initial: 'M',
    avatarColor: 'bg-blue-50 border-blue-200 text-blue-600',
    bio: 'I rate everything. Mostly 3 stars. Brutally honest.',
    ratings: 412,
    reviews: 12,
    following: 89,
    followers: 128,
    avgScore: 3.2,
    distribution: [20, 32, 48, 56, 64, 52, 44, 36, 28, 20],
    topGenres: [
      { name: 'K-Pop', count: 78 },
      { name: 'Hip-Hop', count: 62 },
      { name: 'Pop', count: 54 },
      { name: 'Electronic', count: 42 },
      { name: 'Rock', count: 38 },
    ],
    insights: [
      "You rate much lower than most — a tough critic",
      "Only 3% of your ratings are perfect scores",
      "You rate fast — 412 ratings but only 12 reviews",
    ],
    relationshipInsights: [
      "You both listen to Hip-Hop, but your other genres differ",
      "minwave rates 0.6 points lower on average — tough critic",
      "You both loved Broken Mirror — rare agreement",
      "They've explored way more K-Pop than you have",
      "Their #1 genre (K-Pop) is only your #4",
    ],
    pinnedAlbumIds: ['get-up', 'map-of-the-soul', 'palette', 'omg', 'love-yourself', null, null, null, null],
    badges: ['Tough critic', 'K-Pop explorer'],
  },
  soundwatcher: {
    id: 'soundwatcher',
    name: 'soundwatcher',
    handle: '@soundwatcher',
    initial: 'S',
    avatarColor: 'bg-emerald-50 border-emerald-200 text-emerald-600',
    bio: 'Producer by day, listener by night. I hear things you miss.',
    ratings: 312,
    reviews: 67,
    following: 134,
    followers: 567,
    avgScore: 3.9,
    distribution: [12, 16, 24, 30, 42, 50, 54, 48, 40, 30],
    topGenres: [
      { name: 'Electronic', count: 72 },
      { name: 'Alternative', count: 58 },
      { name: 'K-R&B', count: 48 },
      { name: 'Jazz', count: 36 },
      { name: 'Indie', count: 32 },
    ],
    insights: [
      "You listen with technical ears — detailed reviews",
      "Electronic and Alternative make up 42% of your catalog",
      "You follow more people than follow you — a discoverer",
    ],
    relationshipInsights: [
      "Strong match — K-R&B in both your top 3",
      "soundwatcher explores Electronic heavily, a gap for you",
      "You both rated Broken Mirror 5.0 — twin taste",
      "They write 67 reviews — you should read them",
      "Their avg score (3.9) is close to yours (3.8)",
    ],
    pinnedAlbumIds: ['broken-mirror', 'night-swimming', 'pacific', 'gravity', '202', 'bleu', 'society', null, null],
    badges: ['Producer ear', 'Deep diver'],
  },
  popwatcher: {
    id: 'popwatcher',
    name: 'popwatcher',
    handle: '@popwatcher',
    initial: 'P',
    avatarColor: 'bg-amber-50 border-amber-200 text-amber-600',
    bio: 'Pop music analyst. Charts & culture. I know what sticks.',
    ratings: 156,
    reviews: 24,
    following: 45,
    followers: 891,
    avgScore: 3.5,
    distribution: [8, 14, 22, 28, 34, 30, 26, 22, 16, 12],
    topGenres: [
      { name: 'Pop', count: 48 },
      { name: 'K-Pop', count: 42 },
      { name: 'R&B', count: 28 },
      { name: 'Dance', count: 22 },
      { name: 'Hip-Hop', count: 16 },
    ],
    insights: [
      "Pop and K-Pop dominate — you follow the charts",
      "You rate selectively — only 156 albums",
      "Your ratings skew toward the mainstream",
    ],
    relationshipInsights: [
      "Limited overlap — Pop is their focus, not yours",
      "You both rated Palette 4.0 — one point of agreement",
      "They've barely explored K-Indie, your top interest",
      "Their follower count (891) far exceeds their following (45)",
      "Very different taste profiles — opposites attract?",
    ],
    pinnedAlbumIds: ['palette', 'get-up', 'omg', 'queendom', 'lilac', null, null, null, null],
    badges: ['Chart watcher', 'Pop specialist'],
  },
};

export const getUserProfile = (id: string): UserProfile | undefined => {
  return userProfiles[id] || undefined;
};

export interface Album {
  id: string;
  title: string;
  artist: string;
  artistId: string;
  year: number;
  type: 'Album' | 'EP' | 'Single' | 'Compilation';
  genres: string[];
  rating?: number;
  avgRating: number;
  ratingCount: number;
  reviewCount: number;
  coverGradient: string;
  tracks?: Track[];
  review?: string;
}

export interface Track {
  number: number;
  title: string;
  duration: string;
}

export interface Artist {
  id: string;
  name: string;
  genres: string[];
  followers: string;
  releases: number;
  avatarGradient: string;
}

export interface Review {
  id: string;
  user: string;
  userInitial: string;
  albumId: string;
  rating: number;
  text: string;
  timeAgo: string;
}

export interface ActivityItem {
  id: string;
  user: string;
  userInitial: string;
  type: 'rating' | 'review';
  albumId: string;
  rating: number;
  text?: string;
  timeAgo: string;
}

export interface Ranking {
  id: string;
  title: string;
  country: string;
  genre: string;
  votes: number;
  coverGradients: string[];
  items: RankingItem[];
}

export interface RankingItem {
  rank: number;
  albumId: string;
  votes: number;
}

export interface CuratedList {
  id: string;
  title: string;
  description: string;
  author: string;
  authorInitial: string;
  albumCount: number;
  createdAt: string;
  albumIds: string[];
}

export const GENRE_COLORS: Record<string, string> = {
  'K-Pop': 'from-rose-100 to-pink-50',
  'K-Indie': 'from-teal-100 to-emerald-50',
  'K-R&B': 'from-violet-100 to-purple-50',
  'K-Rap': 'from-orange-100 to-amber-50',
  'Korean Ballad': 'from-blue-100 to-indigo-50',
  'J-Pop': 'from-sky-100 to-cyan-50',
  'City Pop': 'from-fuchsia-100 to-pink-50',
  'Hip-Hop': 'from-yellow-100 to-orange-50',
  'Indie Pop': 'from-green-100 to-lime-50',
  'Indie Rock': 'from-red-100 to-orange-50',
  'Alternative': 'from-gray-100 to-slate-50',
  'Shoegaze': 'from-indigo-100 to-blue-50',
  'Folk': 'from-amber-100 to-yellow-50',
  'Electronic': 'from-cyan-100 to-teal-50',
  'R&B': 'from-purple-100 to-violet-50',
  'Soul': 'from-pink-100 to-rose-50',
  'Classical': 'from-stone-100 to-gray-50',
  'Pop': 'from-emerald-100 to-green-50',
};

export const COVER_GRADIENTS = [
  'bg-gradient-to-br from-slate-300 to-slate-400',
  'bg-gradient-to-br from-rose-200 to-pink-300',
  'bg-gradient-to-br from-teal-200 to-emerald-300',
  'bg-gradient-to-br from-violet-200 to-purple-300',
  'bg-gradient-to-br from-amber-200 to-orange-300',
  'bg-gradient-to-br from-sky-200 to-cyan-300',
  'bg-gradient-to-br from-indigo-200 to-blue-300',
  'bg-gradient-to-br from-fuchsia-200 to-pink-300',
  'bg-gradient-to-br from-lime-200 to-green-300',
  'bg-gradient-to-br from-red-200 to-rose-300',
  'bg-gradient-to-br from-orange-200 to-amber-300',
  'bg-gradient-to-br from-cyan-200 to-teal-300',
  'bg-gradient-to-br from-emerald-200 to-green-300',
  'bg-gradient-to-br from-blue-200 to-indigo-300',
  'bg-gradient-to-br from-gray-200 to-slate-300',
  'bg-gradient-to-br from-stone-200 to-zinc-300',
  'bg-gradient-to-br from-yellow-200 to-lime-300',
  'bg-gradient-to-br from-purple-200 to-violet-300',
  'bg-gradient-to-br from-pink-200 to-rose-300',
  'bg-gradient-to-br from-green-200 to-emerald-300',
];

export const artists: Artist[] = [
  { id: 'iu', name: 'IU', genres: ['K-Pop', 'Korean Ballad', 'Indie Pop'], followers: '4.6M', releases: 18, avatarGradient: 'from-rose-100 to-pink-200' },
  { id: 'newjeans', name: 'NewJeans', genres: ['K-Pop'], followers: '2.1M', releases: 6, avatarGradient: 'from-teal-100 to-emerald-200' },
  { id: 'bts', name: 'BTS', genres: ['K-Pop', 'Hip-Hop'], followers: '12.4M', releases: 24, avatarGradient: 'from-violet-100 to-purple-200' },
  { id: 'blackpink', name: 'BLACKPINK', genres: ['K-Pop'], followers: '8.9M', releases: 12, avatarGradient: 'from-fuchsia-100 to-pink-200' },
  { id: 'offonoff', name: 'offonoff', genres: ['K-R&B', 'Indie Pop'], followers: '340K', releases: 4, avatarGradient: 'from-sky-100 to-cyan-200' },
  { id: 'hyukoh', name: 'Hyukoh', genres: ['K-Indie', 'Indie Rock'], followers: '520K', releases: 7, avatarGradient: 'from-amber-100 to-orange-200' },
  { id: 'dean', name: 'Dean', genres: ['K-R&B', 'Hip-Hop'], followers: '1.2M', releases: 9, avatarGradient: 'from-indigo-100 to-blue-200' },
  { id: 'ziont', name: 'Zion.T', genres: ['K-R&B', 'Soul'], followers: '890K', releases: 11, avatarGradient: 'from-lime-100 to-green-200' },
  { id: 'colde', name: 'Colde', genres: ['K-R&B', 'Indie Pop'], followers: '410K', releases: 6, avatarGradient: 'from-cyan-100 to-teal-200' },
  { id: 'crush', name: 'Crush', genres: ['K-R&B', 'Pop'], followers: '1.5M', releases: 14, avatarGradient: 'from-purple-100 to-violet-200' },
  { id: 'straykids', name: 'Stray Kids', genres: ['K-Pop', 'Hip-Hop'], followers: '3.2M', releases: 16, avatarGradient: 'from-red-100 to-rose-200' },
  { id: 'lesserafim', name: 'LE SSERAFIM', genres: ['K-Pop'], followers: '1.8M', releases: 8, avatarGradient: 'from-emerald-100 to-green-200' },
  { id: 'redvelvet', name: 'Red Velvet', genres: ['K-Pop', 'R&B'], followers: '5.1M', releases: 20, avatarGradient: 'from-pink-100 to-rose-200' },
  { id: 'silicagel', name: 'Silica Gel', genres: ['K-Indie', 'Shoegaze'], followers: '120K', releases: 4, avatarGradient: 'from-stone-100 to-zinc-200' },
  { id: 'ph1', name: 'pH-1', genres: ['K-Rap', 'Hip-Hop'], followers: '680K', releases: 10, avatarGradient: 'from-yellow-100 to-amber-200' },
  { id: 'heize', name: 'Heize', genres: ['K-R&B', 'Pop'], followers: '920K', releases: 12, avatarGradient: 'from-blue-100 to-indigo-200' },
  { id: 'suran', name: 'Suran', genres: ['K-R&B', 'Indie Pop'], followers: '380K', releases: 5, avatarGradient: 'from-orange-100 to-yellow-200' },
  { id: 'jimin', name: 'Jimin', genres: ['K-Pop', 'R&B'], followers: '3.8M', releases: 3, avatarGradient: 'from-violet-100 to-purple-200' },
  { id: 'isora', name: '이소라', genres: ['Korean Ballad', 'K-Indie'], followers: '210K', releases: 8, avatarGradient: 'from-gray-100 to-slate-200' },
  { id: 'yozo', name: '요조', genres: ['K-Indie', 'Folk'], followers: '85K', releases: 4, avatarGradient: 'from-amber-100 to-yellow-200' },
  { id: 'sultandisco', name: '술탄 오브 더 디스코', genres: ['K-Indie', 'Alternative'], followers: '95K', releases: 5, avatarGradient: 'from-red-100 to-orange-200' },
  { id: 'saesonyeon', name: '새소년', genres: ['K-Indie', 'Indie Rock'], followers: '140K', releases: 4, avatarGradient: 'from-teal-100 to-emerald-200' },
  { id: 'gangtaegu', name: '강태구', genres: ['K-R&B', 'Soul'], followers: '75K', releases: 3, avatarGradient: 'from-sky-100 to-cyan-200' },
  { id: 'loco', name: 'Loco', genres: ['K-Rap', 'Hip-Hop'], followers: '780K', releases: 13, avatarGradient: 'from-lime-100 to-green-200' },
  { id: 'mariya', name: 'Mariya Takeuchi', genres: ['City Pop', 'J-Pop'], followers: '1.1M', releases: 22, avatarGradient: 'from-pink-100 to-fuchsia-200' },
  { id: 'hosono', name: 'Haruomi Hosono', genres: ['City Pop', 'Electronic'], followers: '890K', releases: 35, avatarGradient: 'from-cyan-100 to-teal-200' },
  { id: 'yamashita', name: 'Tatsuro Yamashita', genres: ['City Pop', 'J-Pop'], followers: '1.3M', releases: 28, avatarGradient: 'from-orange-100 to-amber-200' },
  { id: 'matsubara', name: 'Miki Matsubara', genres: ['City Pop', 'J-Pop'], followers: '760K', releases: 15, avatarGradient: 'from-purple-100 to-violet-200' },
];

export const albums: Album[] = [
  {
    id: 'broken-mirror',
    title: 'Broken Mirror',
    artist: 'offonoff',
    artistId: 'offonoff',
    year: 2017,
    type: 'Album',
    genres: ['K-R&B', 'Indie Pop'],
    rating: 5.0,
    avgRating: 4.3,
    ratingCount: 142,
    reviewCount: 28,
    coverGradient: 'bg-gradient-to-br from-sky-300 to-indigo-400',
    tracks: [
      { number: 1, title: 'Intro', duration: '1:03' },
      { number: 2, title: 'Coffee (feat. Jennie)', duration: '3:41' },
      { number: 3, title: 'Broken Mirror', duration: '4:12' },
      { number: 4, title: 'Boy', duration: '3:58' },
      { number: 5, title: 'Blossom', duration: '4:34' },
      { number: 6, title: 'Cloudy', duration: '3:22' },
      { number: 7, title: 'Just a Feeling', duration: '5:01' },
      { number: 8, title: 'Glass', duration: '3:47' },
      { number: 9, title: 'Outro', duration: '2:18' },
    ],
    review: "Best Korean indie album of the decade for me.",
  },
  {
    id: 'midsummer-night',
    title: 'Midsummer Night',
    artist: 'IU',
    artistId: 'iu',
    year: 2013,
    type: 'EP',
    genres: ['K-Pop', 'Indie Pop'],
    rating: 4.5,
    avgRating: 4.2,
    ratingCount: 89,
    reviewCount: 14,
    coverGradient: 'bg-gradient-to-br from-amber-200 to-rose-300',
  },
  {
    id: 'get-up',
    title: 'Get Up',
    artist: 'NewJeans',
    artistId: 'newjeans',
    year: 2023,
    type: 'EP',
    genres: ['K-Pop'],
    rating: 3.5,
    avgRating: 4.1,
    ratingCount: 210,
    reviewCount: 45,
    coverGradient: 'bg-gradient-to-br from-teal-200 to-emerald-300',
  },
  {
    id: 'palette',
    title: 'Palette',
    artist: 'IU',
    artistId: 'iu',
    year: 2017,
    type: 'Album',
    genres: ['K-Pop', 'Indie Pop'],
    rating: 4.0,
    avgRating: 4.3,
    ratingCount: 156,
    reviewCount: 32,
    coverGradient: 'bg-gradient-to-br from-orange-100 to-amber-200',
  },
  {
    id: 'love-yourself',
    title: 'Love Yourself',
    artist: 'BTS',
    artistId: 'bts',
    year: 2017,
    type: 'Album',
    genres: ['K-Pop', 'Hip-Hop'],
    rating: 4.0,
    avgRating: 4.5,
    ratingCount: 380,
    reviewCount: 62,
    coverGradient: 'bg-gradient-to-br from-violet-200 to-purple-300',
  },
  {
    id: 'seven-seasons',
    title: 'Seven Seasons',
    artist: 'Epik High',
    artistId: 'epikhigh',
    year: 2014,
    type: 'Album',
    genres: ['K-Rap', 'Hip-Hop'],
    rating: 3.0,
    avgRating: 3.8,
    ratingCount: 76,
    reviewCount: 11,
    coverGradient: 'bg-gradient-to-br from-gray-200 to-slate-300',
  },
  {
    id: 'society',
    title: 's o c i e t y',
    artist: 'Dean',
    artistId: 'dean',
    year: 2019,
    type: 'EP',
    genres: ['K-R&B', 'Hip-Hop'],
    avgRating: 4.2,
    ratingCount: 98,
    reviewCount: 19,
    coverGradient: 'bg-gradient-to-br from-indigo-200 to-blue-300',
  },
  {
    id: '24hours',
    title: '24Hours',
    artist: 'Zion.T',
    artistId: 'ziont',
    year: 2018,
    type: 'Single',
    genres: ['K-R&B', 'Soul'],
    avgRating: 3.9,
    ratingCount: 64,
    reviewCount: 8,
    coverGradient: 'bg-gradient-to-br from-lime-200 to-green-300',
  },
  {
    id: 'gravity',
    title: 'Gravity',
    artist: 'Colde',
    artistId: 'colde',
    year: 2020,
    type: 'Album',
    genres: ['K-R&B', 'Indie Pop'],
    avgRating: 4.0,
    ratingCount: 72,
    reviewCount: 12,
    coverGradient: 'bg-gradient-to-br from-cyan-200 to-teal-300',
  },
  {
    id: 'everything',
    title: 'Everything',
    artist: 'Crush',
    artistId: 'crush',
    year: 2020,
    type: 'Album',
    genres: ['K-R&B', 'Pop'],
    avgRating: 4.1,
    ratingCount: 110,
    reviewCount: 21,
    coverGradient: 'bg-gradient-to-br from-purple-200 to-violet-300',
  },
  {
    id: 'still-life',
    title: 'Still Life',
    artist: 'Loco',
    artistId: 'loco',
    year: 2019,
    type: 'Album',
    genres: ['K-Rap', 'Hip-Hop'],
    avgRating: 3.7,
    ratingCount: 58,
    reviewCount: 7,
    coverGradient: 'bg-gradient-to-br from-yellow-200 to-amber-300',
  },
  {
    id: 'when',
    title: 'When',
    artist: 'pH-1',
    artistId: 'ph1',
    year: 2021,
    type: 'EP',
    genres: ['K-Rap', 'Hip-Hop'],
    avgRating: 3.8,
    ratingCount: 45,
    reviewCount: 6,
    coverGradient: 'bg-gradient-to-br from-stone-200 to-zinc-300',
  },
  {
    id: 'daydream',
    title: 'Daydream',
    artist: 'Heize',
    artistId: 'heize',
    year: 2019,
    type: 'Album',
    genres: ['K-R&B', 'Pop'],
    avgRating: 4.0,
    ratingCount: 88,
    reviewCount: 15,
    coverGradient: 'bg-gradient-to-br from-blue-200 to-indigo-300',
  },
  {
    id: 'bliss',
    title: 'Bliss',
    artist: 'Suran',
    artistId: 'suran',
    year: 2020,
    type: 'EP',
    genres: ['K-R&B', 'Indie Pop'],
    avgRating: 3.7,
    ratingCount: 42,
    reviewCount: 5,
    coverGradient: 'bg-gradient-to-br from-orange-200 to-pink-300',
  },
  {
    id: 'omg',
    title: 'OMG',
    artist: 'NewJeans',
    artistId: 'newjeans',
    year: 2023,
    type: 'Single',
    genres: ['K-Pop'],
    avgRating: 4.0,
    ratingCount: 198,
    reviewCount: 38,
    coverGradient: 'bg-gradient-to-br from-pink-200 to-rose-300',
  },
  {
    id: 'the-album',
    title: 'The Album',
    artist: 'BLACKPINK',
    artistId: 'blackpink',
    year: 2020,
    type: 'Album',
    genres: ['K-Pop'],
    avgRating: 3.8,
    ratingCount: 250,
    reviewCount: 48,
    coverGradient: 'bg-gradient-to-br from-fuchsia-200 to-purple-300',
  },
  {
    id: 'map-of-the-soul',
    title: 'Map of the Soul',
    artist: 'BTS',
    artistId: 'bts',
    year: 2020,
    type: 'Album',
    genres: ['K-Pop', 'Hip-Hop'],
    avgRating: 4.4,
    ratingCount: 420,
    reviewCount: 75,
    coverGradient: 'bg-gradient-to-br from-violet-200 to-indigo-300',
  },
  {
    id: 'noeasy',
    title: 'NOEASY',
    artist: 'Stray Kids',
    artistId: 'straykids',
    year: 2021,
    type: 'Album',
    genres: ['K-Pop', 'Hip-Hop'],
    avgRating: 3.9,
    ratingCount: 180,
    reviewCount: 31,
    coverGradient: 'bg-gradient-to-br from-red-200 to-rose-300',
  },
  {
    id: 'pink-venom',
    title: 'Pink Venom',
    artist: 'BLACKPINK',
    artistId: 'blackpink',
    year: 2022,
    type: 'Single',
    genres: ['K-Pop'],
    avgRating: 3.6,
    ratingCount: 210,
    reviewCount: 40,
    coverGradient: 'bg-gradient-to-br from-pink-200 to-fuchsia-300',
  },
  {
    id: 'proof',
    title: 'Proof',
    artist: 'BTS',
    artistId: 'bts',
    year: 2022,
    type: 'Compilation',
    genres: ['K-Pop', 'Hip-Hop'],
    avgRating: 4.2,
    ratingCount: 310,
    reviewCount: 52,
    coverGradient: 'bg-gradient-to-br from-purple-200 to-violet-300',
  },
  {
    id: 'antifragile',
    title: 'ANTIFRAGILE',
    artist: 'LE SSERAFIM',
    artistId: 'lesserafim',
    year: 2022,
    type: 'EP',
    genres: ['K-Pop'],
    avgRating: 3.8,
    ratingCount: 165,
    reviewCount: 28,
    coverGradient: 'bg-gradient-to-br from-emerald-200 to-green-300',
  },
  {
    id: 'queendom',
    title: 'Queendom',
    artist: 'Red Velvet',
    artistId: 'redvelvet',
    year: 2021,
    type: 'EP',
    genres: ['K-Pop', 'R&B'],
    avgRating: 4.0,
    ratingCount: 145,
    reviewCount: 24,
    coverGradient: 'bg-gradient-to-br from-rose-200 to-pink-300',
  },
  {
    id: 'her',
    title: 'Her',
    artist: 'Hyukoh',
    artistId: 'hyukoh',
    year: 2016,
    type: 'Album',
    genres: ['K-Indie', 'Indie Rock'],
    avgRating: 4.3,
    ratingCount: 112,
    reviewCount: 22,
    coverGradient: 'bg-gradient-to-br from-amber-200 to-orange-300',
  },
  {
    id: '23',
    title: '23',
    artist: 'Hyukoh',
    artistId: 'hyukoh',
    year: 2014,
    type: 'Album',
    genres: ['K-Indie', 'Indie Rock'],
    avgRating: 4.1,
    ratingCount: 86,
    reviewCount: 14,
    coverGradient: 'bg-gradient-to-br from-teal-200 to-cyan-300',
  },
  {
    id: 'seonmul',
    title: '선물',
    artist: '이소라',
    artistId: 'isora',
    year: 2019,
    type: 'Album',
    genres: ['Korean Ballad', 'K-Indie'],
    avgRating: 4.0,
    ratingCount: 48,
    reviewCount: 7,
    coverGradient: 'bg-gradient-to-br from-gray-200 to-stone-300',
  },
  {
    id: 'japcho',
    title: '잡초',
    artist: '요조',
    artistId: 'yozo',
    year: 2016,
    type: 'EP',
    genres: ['K-Indie', 'Folk'],
    avgRating: 3.8,
    ratingCount: 32,
    reviewCount: 4,
    coverGradient: 'bg-gradient-to-br from-yellow-200 to-lime-300',
  },
  {
    id: 'night-swimming',
    title: 'Night Swimming',
    artist: 'Silica Gel',
    artistId: 'silicagel',
    year: 2022,
    type: 'Album',
    genres: ['K-Indie', 'Shoegaze'],
    avgRating: 4.2,
    ratingCount: 68,
    reviewCount: 13,
    coverGradient: 'bg-gradient-to-br from-slate-300 to-gray-400',
  },
  {
    id: 'aaa',
    title: 'AAA',
    artist: '아이유',
    artistId: 'iu',
    year: 2015,
    type: 'EP',
    genres: ['K-Indie', 'Folk'],
    avgRating: 3.7,
    ratingCount: 54,
    reviewCount: 6,
    coverGradient: 'bg-gradient-to-br from-green-200 to-emerald-300',
  },
  {
    id: 'bleu',
    title: 'bleu',
    artist: '강태구',
    artistId: 'gangtaegu',
    year: 2020,
    type: 'Album',
    genres: ['K-R&B', 'Soul'],
    avgRating: 4.1,
    ratingCount: 56,
    reviewCount: 10,
    coverGradient: 'bg-gradient-to-br from-sky-200 to-blue-300',
  },
  {
    id: '180',
    title: '180',
    artist: 'offonoff',
    artistId: 'offonoff',
    year: 2018,
    type: 'EP',
    genres: ['K-R&B', 'Indie Pop'],
    avgRating: 3.9,
    ratingCount: 72,
    reviewCount: 11,
    coverGradient: 'bg-gradient-to-br from-indigo-200 to-violet-300',
  },
  {
    id: '24',
    title: '24',
    artist: 'Zion.T',
    artistId: 'ziont',
    year: 2017,
    type: 'Album',
    genres: ['K-R&B', 'Soul'],
    avgRating: 4.0,
    ratingCount: 82,
    reviewCount: 14,
    coverGradient: 'bg-gradient-to-br from-lime-200 to-teal-300',
  },
  {
    id: '202',
    title: '202',
    artist: 'Dean',
    artistId: 'dean',
    year: 2016,
    type: 'EP',
    genres: ['K-R&B', 'Hip-Hop'],
    avgRating: 4.2,
    ratingCount: 95,
    reviewCount: 17,
    coverGradient: 'bg-gradient-to-br from-blue-200 to-indigo-300',
  },
  {
    id: 'summer-love',
    title: 'Summer Love',
    artist: 'Crush',
    artistId: 'crush',
    year: 2018,
    type: 'EP',
    genres: ['K-R&B', 'Pop'],
    avgRating: 3.8,
    ratingCount: 78,
    reviewCount: 12,
    coverGradient: 'bg-gradient-to-br from-orange-200 to-yellow-300',
  },
  {
    id: 'grown',
    title: 'Grown',
    artist: 'pH-1',
    artistId: 'ph1',
    year: 2020,
    type: 'Album',
    genres: ['K-Rap', 'Hip-Hop'],
    avgRating: 3.7,
    ratingCount: 52,
    reviewCount: 8,
    coverGradient: 'bg-gradient-to-br from-stone-200 to-amber-300',
  },
  {
    id: 'plastic-love',
    title: 'Plastic Love',
    artist: 'Mariya Takeuchi',
    artistId: 'mariya',
    year: 1984,
    type: 'Single',
    genres: ['City Pop', 'J-Pop'],
    avgRating: 4.5,
    ratingCount: 230,
    reviewCount: 42,
    coverGradient: 'bg-gradient-to-br from-pink-200 to-fuchsia-300',
  },
  {
    id: 'pacific',
    title: 'Pacific',
    artist: 'Haruomi Hosono',
    artistId: 'hosono',
    year: 1978,
    type: 'Album',
    genres: ['City Pop', 'Electronic'],
    avgRating: 4.3,
    ratingCount: 120,
    reviewCount: 22,
    coverGradient: 'bg-gradient-to-br from-cyan-200 to-teal-300',
  },
  {
    id: 'surf-rain',
    title: 'Surf & Rain',
    artist: 'Tatsuro Yamashita',
    artistId: 'yamashita',
    year: 1982,
    type: 'Album',
    genres: ['City Pop', 'J-Pop'],
    avgRating: 4.4,
    ratingCount: 145,
    reviewCount: 28,
    coverGradient: 'bg-gradient-to-br from-orange-200 to-amber-300',
  },
  {
    id: 'for-you',
    title: 'For You',
    artist: 'Miki Matsubara',
    artistId: 'matsubara',
    year: 1982,
    type: 'Album',
    genres: ['City Pop', 'J-Pop'],
    avgRating: 4.2,
    ratingCount: 110,
    reviewCount: 19,
    coverGradient: 'bg-gradient-to-br from-purple-200 to-violet-300',
  },
  {
    id: 'niagara-triangle',
    title: 'Niagara Triangle',
    artist: 'Various Artists',
    artistId: 'various',
    year: 1986,
    type: 'Compilation',
    genres: ['City Pop', 'J-Pop'],
    avgRating: 4.0,
    ratingCount: 85,
    reviewCount: 12,
    coverGradient: 'bg-gradient-to-br from-blue-200 to-cyan-300',
  },
  {
    id: 'lilac',
    title: 'LILAC',
    artist: 'IU',
    artistId: 'iu',
    year: 2021,
    type: 'Album',
    genres: ['K-Pop', 'Indie Pop'],
    avgRating: 4.2,
    ratingCount: 178,
    reviewCount: 35,
    coverGradient: 'bg-gradient-to-br from-violet-200 to-purple-300',
  },
  {
    id: 'chat-shire',
    title: 'Chat-Shire',
    artist: 'IU',
    artistId: 'iu',
    year: 2015,
    type: 'EP',
    genres: ['K-Pop', 'Indie Pop'],
    avgRating: 3.8,
    ratingCount: 98,
    reviewCount: 16,
    coverGradient: 'bg-gradient-to-br from-pink-200 to-rose-300',
  },
  {
    id: 'modern-times',
    title: 'Modern Times',
    artist: 'IU',
    artistId: 'iu',
    year: 2013,
    type: 'Album',
    genres: ['K-Pop', 'Indie Pop'],
    avgRating: 4.0,
    ratingCount: 112,
    reviewCount: 19,
    coverGradient: 'bg-gradient-to-br from-amber-200 to-yellow-300',
  },
  {
    id: 'the-shower',
    title: 'The Shower',
    artist: 'IU',
    artistId: 'iu',
    year: 2018,
    type: 'Single',
    genres: ['Korean Ballad'],
    avgRating: 3.9,
    ratingCount: 88,
    reviewCount: 13,
    coverGradient: 'bg-gradient-to-br from-sky-200 to-cyan-300',
  },
  {
    id: 'real',
    title: 'Real',
    artist: 'IU',
    artistId: 'iu',
    year: 2010,
    type: 'Album',
    genres: ['K-Pop'],
    avgRating: 3.6,
    ratingCount: 72,
    reviewCount: 9,
    coverGradient: 'bg-gradient-to-br from-green-200 to-emerald-300',
  },
  {
    id: 'last-fantasy',
    title: 'Last Fantasy',
    artist: 'IU',
    artistId: 'iu',
    year: 2011,
    type: 'Album',
    genres: ['K-Pop', 'Korean Ballad'],
    avgRating: 3.7,
    ratingCount: 85,
    reviewCount: 11,
    coverGradient: 'bg-gradient-to-br from-rose-200 to-pink-300',
  },
  {
    id: 'face',
    title: 'FACE',
    artist: 'Jimin',
    artistId: 'jimin',
    year: 2023,
    type: 'Album',
    genres: ['K-Pop', 'R&B'],
    rating: 3.0,
    avgRating: 3.8,
    ratingCount: 140,
    reviewCount: 25,
    coverGradient: 'bg-gradient-to-br from-indigo-200 to-violet-300',
  },
  {
    id: 'dream',
    title: 'Dream',
    artist: 'IU',
    artistId: 'iu',
    year: 2021,
    type: 'Single',
    genres: ['K-Pop'],
    avgRating: 3.5,
    ratingCount: 65,
    reviewCount: 8,
    coverGradient: 'bg-gradient-to-br from-teal-200 to-emerald-300',
  },
  {
    id: 'sober',
    title: 'Sober',
    artist: 'Hyukoh',
    artistId: 'hyukoh',
    year: 2015,
    type: 'Album',
    genres: ['K-Indie', 'Indie Rock'],
    avgRating: 4.0,
    ratingCount: 74,
    reviewCount: 12,
    coverGradient: 'bg-gradient-to-br from-gray-200 to-slate-300',
  },
  {
    id: 'midsummer-sweetness',
    title: "Midsummer Night's Sweetness",
    artist: 'IU',
    artistId: 'iu',
    year: 2013,
    type: 'Single',
    genres: ['K-Pop', 'Indie Pop'],
    avgRating: 3.8,
    ratingCount: 92,
    reviewCount: 14,
    coverGradient: 'bg-gradient-to-br from-amber-200 to-orange-300',
  },
  {
    id: 'so-nyeon-i-onda',
    title: '소년이 온다',
    artist: '술탄 오브 더 디스코',
    artistId: 'sultandisco',
    year: 2018,
    type: 'Album',
    genres: ['K-Indie', 'Alternative'],
    avgRating: 3.9,
    ratingCount: 38,
    reviewCount: 5,
    coverGradient: 'bg-gradient-to-br from-red-200 to-orange-300',
  },
  {
    id: 'realists',
    title: 'Realists',
    artist: '새소년',
    artistId: 'saesonyeon',
    year: 2021,
    type: 'Album',
    genres: ['K-Indie', 'Indie Rock'],
    avgRating: 4.0,
    ratingCount: 52,
    reviewCount: 8,
    coverGradient: 'bg-gradient-to-br from-teal-200 to-emerald-300',
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    user: 'kenneth',
    userInitial: 'K',
    albumId: 'broken-mirror',
    rating: 5.0,
    text: "Best Korean indie album of the decade for me. The production is impossibly delicate.",
    timeAgo: '2d ago',
  },
  {
    id: 'r2',
    user: 'jiyeon_music',
    userInitial: 'J',
    albumId: 'broken-mirror',
    rating: 4.5,
    text: "Coffee feat. Jennie is one of the most played songs in my library. The whole record breathes.",
    timeAgo: '5d ago',
  },
  {
    id: 'r3',
    user: 'soundwatcher',
    userInitial: 'S',
    albumId: 'broken-mirror',
    rating: 4.0,
    text: "Hauntingly minimalist. The kind of album that rewards repeated listening.",
    timeAgo: '1w ago',
  },
  {
    id: 'r4',
    user: 'kenneth',
    userInitial: 'K',
    albumId: 'palette',
    rating: 4.0,
    text: "IU at her most assured. Every track feels like a personal letter.",
    timeAgo: '5d ago',
  },
  {
    id: 'r5',
    user: 'minwave',
    userInitial: 'M',
    albumId: 'bleu',
    rating: 5.0,
    text: "An absolutely gorgeous record from start to finish.",
    timeAgo: '1w ago',
  },
  {
    id: 'r6',
    user: 'popwatcher',
    userInitial: 'P',
    albumId: 'her',
    rating: 3.0,
    text: "Not my favorite Hyukoh but still solid.",
    timeAgo: '1w ago',
  },
];

export const activityFeed: ActivityItem[] = [
  {
    id: 'a1',
    user: 'kenneth',
    userInitial: 'K',
    type: 'review',
    albumId: 'broken-mirror',
    rating: 5.0,
    text: "Best Korean indie album of the decade for me. The production is impossibly delicate.",
    timeAgo: '2d ago',
  },
  {
    id: 'a2',
    user: 'jiyeon_music',
    userInitial: 'J',
    type: 'rating',
    albumId: 'omg',
    rating: 4.5,
    timeAgo: '3d ago',
  },
  {
    id: 'a3',
    user: 'soundwatcher',
    userInitial: 'S',
    type: 'review',
    albumId: 'palette',
    rating: 4.0,
    text: "IU at her most assured. Every track feels like a personal letter.",
    timeAgo: '5d ago',
  },
  {
    id: 'a4',
    user: 'minwave',
    userInitial: 'M',
    type: 'rating',
    albumId: 'bleu',
    rating: 5.0,
    timeAgo: '1w ago',
  },
  {
    id: 'a5',
    user: 'popwatcher',
    userInitial: 'P',
    type: 'rating',
    albumId: 'her',
    rating: 3.0,
    timeAgo: '1w ago',
  },
];

export const rankings: Ranking[] = [
  // ── Global ──
  {
    id: 'global-pop',
    title: 'Best Pop Albums',
    country: 'Global',
    genre: 'Pop',
    votes: 1240,
    coverGradients: ['bg-gradient-to-br from-pink-200 to-rose-300', 'bg-gradient-to-br from-orange-200 to-amber-300', 'bg-gradient-to-br from-teal-200 to-emerald-300', 'bg-gradient-to-br from-violet-200 to-purple-300'],
    items: [{ rank: 1, albumId: 'palette', votes: 120 }, { rank: 2, albumId: 'the-album', votes: 98 }, { rank: 3, albumId: 'map-of-the-soul', votes: 87 }, { rank: 4, albumId: 'plastic-love', votes: 76 }, { rank: 5, albumId: 'lilac', votes: 65 }],
  },
  {
    id: 'global-rock',
    title: 'Best Rock Albums',
    country: 'Global',
    genre: 'Rock',
    votes: 890,
    coverGradients: ['bg-gradient-to-br from-red-200 to-orange-300', 'bg-gradient-to-br from-gray-200 to-slate-300', 'bg-gradient-to-br from-stone-200 to-zinc-300', 'bg-gradient-to-br from-amber-200 to-yellow-300'],
    items: [{ rank: 1, albumId: 'her', votes: 94 }, { rank: 2, albumId: '23', votes: 82 }, { rank: 3, albumId: 'realists', votes: 71 }, { rank: 4, albumId: 'so-nyeon-i-onda', votes: 58 }, { rank: 5, albumId: 'still-life', votes: 45 }],
  },
  {
    id: 'global-hiphop',
    title: 'Best Hip-Hop Albums',
    country: 'Global',
    genre: 'Hip-Hop',
    votes: 756,
    coverGradients: ['bg-gradient-to-br from-yellow-200 to-amber-300', 'bg-gradient-to-br from-orange-200 to-red-300', 'bg-gradient-to-br from-lime-200 to-green-300', 'bg-gradient-to-br from-stone-200 to-gray-300'],
    items: [{ rank: 1, albumId: 'map-of-the-soul', votes: 88 }, { rank: 2, albumId: 'noeasy', votes: 74 }, { rank: 3, albumId: 'grown', votes: 62 }, { rank: 4, albumId: 'when', votes: 51 }, { rank: 5, albumId: 'still-life', votes: 43 }],
  },
  {
    id: 'global-rnb',
    title: 'Best R&B Albums',
    country: 'Global',
    genre: 'R&B',
    votes: 932,
    coverGradients: ['bg-gradient-to-br from-purple-200 to-violet-300', 'bg-gradient-to-br from-indigo-200 to-blue-300', 'bg-gradient-to-br from-pink-200 to-fuchsia-300', 'bg-gradient-to-br from-cyan-200 to-teal-300'],
    items: [{ rank: 1, albumId: '202', votes: 102 }, { rank: 2, albumId: 'bleu', votes: 89 }, { rank: 3, albumId: 'everything', votes: 76 }, { rank: 4, albumId: 'daydream', votes: 64 }, { rank: 5, albumId: '24', votes: 55 }],
  },
  {
    id: 'global-electronic',
    title: 'Best Electronic Albums',
    country: 'Global',
    genre: 'Electronic',
    votes: 412,
    coverGradients: ['bg-gradient-to-br from-cyan-200 to-teal-300', 'bg-gradient-to-br from-sky-200 to-blue-300', 'bg-gradient-to-br from-emerald-200 to-green-300', 'bg-gradient-to-br from-violet-200 to-purple-300'],
    items: [{ rank: 1, albumId: 'pacific', votes: 56 }, { rank: 2, albumId: 'night-swimming', votes: 48 }, { rank: 3, albumId: 'gravity', votes: 42 }, { rank: 4, albumId: 'surf-rain', votes: 38 }, { rank: 5, albumId: 'for-you', votes: 31 }],
  },
  {
    id: 'global-folk',
    title: 'Best Folk Albums',
    country: 'Global',
    genre: 'Folk',
    votes: 298,
    coverGradients: ['bg-gradient-to-br from-amber-200 to-yellow-300', 'bg-gradient-to-br from-green-200 to-emerald-300', 'bg-gradient-to-br from-orange-200 to-lime-300', 'bg-gradient-to-br from-stone-200 to-zinc-300'],
    items: [{ rank: 1, albumId: 'seonmul', votes: 42 }, { rank: 2, albumId: 'japcho', votes: 38 }, { rank: 3, albumId: 'aaa', votes: 34 }, { rank: 4, albumId: 'modern-times', votes: 28 }, { rank: 5, albumId: 'chat-shire', votes: 22 }],
  },
  {
    id: 'global-alternative',
    title: 'Best Alternative Albums',
    country: 'Global',
    genre: 'Alternative',
    votes: 534,
    coverGradients: ['bg-gradient-to-br from-slate-300 to-gray-400', 'bg-gradient-to-br from-teal-200 to-cyan-300', 'bg-gradient-to-br from-indigo-200 to-violet-300', 'bg-gradient-to-br from-gray-200 to-stone-300'],
    items: [{ rank: 1, albumId: 'night-swimming', votes: 68 }, { rank: 2, albumId: 'broken-mirror', votes: 59 }, { rank: 3, albumId: 'her', votes: 52 }, { rank: 4, albumId: 'so-nyeon-i-onda', votes: 44 }, { rank: 5, albumId: 'realists', votes: 38 }],
  },
  {
    id: 'global-indie-rock',
    title: 'Best Indie Rock Albums',
    country: 'Global',
    genre: 'Indie Rock',
    votes: 478,
    coverGradients: ['bg-gradient-to-br from-red-200 to-rose-300', 'bg-gradient-to-br from-orange-200 to-amber-300', 'bg-gradient-to-br from-teal-200 to-emerald-300', 'bg-gradient-to-br from-gray-200 to-slate-300'],
    items: [{ rank: 1, albumId: 'her', votes: 72 }, { rank: 2, albumId: '23', votes: 64 }, { rank: 3, albumId: 'realists', votes: 55 }, { rank: 4, albumId: 'so-nyeon-i-onda', votes: 47 }, { rank: 5, albumId: 'broken-mirror', votes: 39 }],
  },
  {
    id: 'global-shoegaze',
    title: 'Best Shoegaze Albums',
    country: 'Global',
    genre: 'Shoegaze',
    votes: 312,
    coverGradients: ['bg-gradient-to-br from-slate-300 to-gray-400', 'bg-gradient-to-br from-blue-200 to-indigo-300', 'bg-gradient-to-br from-violet-200 to-purple-300', 'bg-gradient-to-br from-cyan-200 to-teal-300'],
    items: [{ rank: 1, albumId: 'night-swimming', votes: 48 }, { rank: 2, albumId: 'her', votes: 42 }, { rank: 3, albumId: '23', votes: 36 }, { rank: 4, albumId: 'realists', votes: 30 }, { rank: 5, albumId: 'so-nyeon-i-onda', votes: 25 }],
  },
  {
    id: 'global-classical',
    title: 'Best Classical Albums',
    country: 'Global',
    genre: 'Classical',
    votes: 156,
    coverGradients: ['bg-gradient-to-br from-stone-200 to-gray-300', 'bg-gradient-to-br from-amber-200 to-yellow-300', 'bg-gradient-to-br from-slate-200 to-zinc-300', 'bg-gradient-to-br from-emerald-200 to-teal-300'],
    items: [{ rank: 1, albumId: 'seonmul', votes: 28 }, { rank: 2, albumId: 'palette', votes: 24 }, { rank: 3, albumId: 'japcho', votes: 20 }, { rank: 4, albumId: 'modern-times', votes: 16 }, { rank: 5, albumId: 'chat-shire', votes: 12 }],
  },

  // ── Korea ──
  {
    id: 'korea-kpop',
    title: 'Best K-Pop Albums',
    country: 'Korea',
    genre: 'K-Pop',
    votes: 2180,
    coverGradients: ['bg-gradient-to-br from-pink-200 to-rose-300', 'bg-gradient-to-br from-teal-200 to-emerald-300', 'bg-gradient-to-br from-violet-200 to-purple-300', 'bg-gradient-to-br from-fuchsia-200 to-pink-300'],
    items: [{ rank: 1, albumId: 'map-of-the-soul', votes: 142 }, { rank: 2, albumId: 'palette', votes: 118 }, { rank: 3, albumId: 'the-album', votes: 95 }, { rank: 4, albumId: 'lilac', votes: 82 }, { rank: 5, albumId: 'queendom', votes: 74 }],
  },
  {
    id: 'korea-k-indie',
    title: 'Best K-Indie Albums',
    country: 'Korea',
    genre: 'K-Indie',
    votes: 1560,
    coverGradients: ['bg-gradient-to-br from-sky-200 to-indigo-300', 'bg-gradient-to-br from-amber-200 to-orange-300', 'bg-gradient-to-br from-slate-200 to-gray-300', 'bg-gradient-to-br from-teal-200 to-emerald-300'],
    items: [{ rank: 1, albumId: 'broken-mirror', votes: 168 }, { rank: 2, albumId: 'her', votes: 144 }, { rank: 3, albumId: 'night-swimming', votes: 121 }, { rank: 4, albumId: '23', votes: 98 }, { rank: 5, albumId: 'seonmul', votes: 87 }],
  },
  {
    id: 'korea-krnb',
    title: 'Best K-R&B Albums',
    country: 'Korea',
    genre: 'K-R&B',
    votes: 1240,
    coverGradients: ['bg-gradient-to-br from-indigo-200 to-blue-300', 'bg-gradient-to-br from-purple-200 to-violet-300', 'bg-gradient-to-br from-lime-200 to-green-300', 'bg-gradient-to-br from-cyan-200 to-teal-300'],
    items: [{ rank: 1, albumId: '202', votes: 112 }, { rank: 2, albumId: 'bleu', votes: 98 }, { rank: 3, albumId: 'everything', votes: 87 }, { rank: 4, albumId: 'daydream', votes: 76 }, { rank: 5, albumId: '24', votes: 65 }],
  },
  {
    id: 'korea-krap',
    title: 'Best K-Rap Albums',
    country: 'Korea',
    genre: 'K-Rap',
    votes: 876,
    coverGradients: ['bg-gradient-to-br from-yellow-200 to-amber-300', 'bg-gradient-to-br from-gray-200 to-slate-300', 'bg-gradient-to-br from-stone-200 to-zinc-300', 'bg-gradient-to-br from-orange-200 to-red-300'],
    items: [{ rank: 1, albumId: 'map-of-the-soul', votes: 78 }, { rank: 2, albumId: 'noeasy', votes: 68 }, { rank: 3, albumId: 'grown', votes: 58 }, { rank: 4, albumId: 'when', votes: 49 }, { rank: 5, albumId: 'still-life', votes: 42 }],
  },
  {
    id: 'korea-ballad',
    title: 'Best Korean Ballad Albums',
    country: 'Korea',
    genre: 'Korean Ballad',
    votes: 654,
    coverGradients: ['bg-gradient-to-br from-blue-200 to-indigo-300', 'bg-gradient-to-br from-sky-200 to-cyan-300', 'bg-gradient-to-br from-violet-200 to-purple-300', 'bg-gradient-to-br from-pink-200 to-rose-300'],
    items: [{ rank: 1, albumId: 'seonmul', votes: 62 }, { rank: 2, albumId: 'the-shower', votes: 54 }, { rank: 3, albumId: 'last-fantasy', votes: 48 }, { rank: 4, albumId: 'modern-times', votes: 42 }, { rank: 5, albumId: 'real', votes: 36 }],
  },

  // ── Japan ──
  {
    id: 'japan-jpop',
    title: 'Best J-Pop Albums',
    country: 'Japan',
    genre: 'J-Pop',
    votes: 1120,
    coverGradients: ['bg-gradient-to-br from-pink-200 to-rose-300', 'bg-gradient-to-br from-orange-200 to-amber-300', 'bg-gradient-to-br from-teal-200 to-emerald-300', 'bg-gradient-to-br from-sky-200 to-cyan-300'],
    items: [{ rank: 1, albumId: 'surf-rain', votes: 92 }, { rank: 2, albumId: 'plastic-love', votes: 88 }, { rank: 3, albumId: 'for-you', votes: 76 }, { rank: 4, albumId: 'pacific', votes: 64 }, { rank: 5, albumId: 'niagara-triangle', votes: 58 }],
  },
  {
    id: 'japan-citypop',
    title: 'Best City Pop Albums',
    country: 'Japan',
    genre: 'City Pop',
    votes: 1340,
    coverGradients: ['bg-gradient-to-br from-fuchsia-200 to-pink-300', 'bg-gradient-to-br from-orange-200 to-amber-300', 'bg-gradient-to-br from-cyan-200 to-teal-300', 'bg-gradient-to-br from-purple-200 to-violet-300'],
    items: [{ rank: 1, albumId: 'plastic-love', votes: 108 }, { rank: 2, albumId: 'surf-rain', votes: 96 }, { rank: 3, albumId: 'pacific', votes: 84 }, { rank: 4, albumId: 'for-you', votes: 72 }, { rank: 5, albumId: 'niagara-triangle', votes: 64 }],
  },
  {
    id: 'japan-jrock',
    title: 'Best J-Rock Albums',
    country: 'Japan',
    genre: 'J-Rock',
    votes: 534,
    coverGradients: ['bg-gradient-to-br from-red-200 to-orange-300', 'bg-gradient-to-br from-gray-200 to-slate-300', 'bg-gradient-to-br from-amber-200 to-yellow-300', 'bg-gradient-to-br from-teal-200 to-cyan-300'],
    items: [{ rank: 1, albumId: 'surf-rain', votes: 58 }, { rank: 2, albumId: 'pacific', votes: 52 }, { rank: 3, albumId: 'plastic-love', votes: 46 }, { rank: 4, albumId: 'for-you', votes: 40 }, { rank: 5, albumId: 'niagara-triangle', votes: 34 }],
  },

  // ── USA ──
  {
    id: 'usa-pop',
    title: 'Best American Pop Albums',
    country: 'USA',
    genre: 'Pop',
    votes: 1876,
    coverGradients: ['bg-gradient-to-br from-pink-200 to-fuchsia-300', 'bg-gradient-to-br from-violet-200 to-purple-300', 'bg-gradient-to-br from-orange-200 to-amber-300', 'bg-gradient-to-br from-teal-200 to-emerald-300'],
    items: [{ rank: 1, albumId: 'palette', votes: 112 }, { rank: 2, albumId: 'the-album', votes: 98 }, { rank: 3, albumId: 'map-of-the-soul', votes: 86 }, { rank: 4, albumId: 'lilac', votes: 74 }, { rank: 5, albumId: 'queendom', votes: 66 }],
  },
  {
    id: 'usa-hiphop',
    title: 'Best American Hip-Hop Albums',
    country: 'USA',
    genre: 'Hip-Hop',
    votes: 1654,
    coverGradients: ['bg-gradient-to-br from-yellow-200 to-amber-300', 'bg-gradient-to-br from-orange-200 to-red-300', 'bg-gradient-to-br from-lime-200 to-green-300', 'bg-gradient-to-br from-stone-200 to-gray-300'],
    items: [{ rank: 1, albumId: 'map-of-the-soul', votes: 98 }, { rank: 2, albumId: 'noeasy', votes: 86 }, { rank: 3, albumId: 'grown', votes: 74 }, { rank: 4, albumId: 'when', votes: 64 }, { rank: 5, albumId: 'still-life', votes: 56 }],
  },
  {
    id: 'usa-rnb',
    title: 'Best American R&B Albums',
    country: 'USA',
    genre: 'R&B',
    votes: 1432,
    coverGradients: ['bg-gradient-to-br from-purple-200 to-violet-300', 'bg-gradient-to-br from-indigo-200 to-blue-300', 'bg-gradient-to-br from-pink-200 to-rose-300', 'bg-gradient-to-br from-cyan-200 to-teal-300'],
    items: [{ rank: 1, albumId: '202', votes: 112 }, { rank: 2, albumId: 'bleu', votes: 98 }, { rank: 3, albumId: 'everything', votes: 86 }, { rank: 4, albumId: 'daydream', votes: 74 }, { rank: 5, albumId: '24', votes: 64 }],
  },
  {
    id: 'usa-rock',
    title: 'Best American Rock Albums',
    country: 'USA',
    genre: 'Rock',
    votes: 876,
    coverGradients: ['bg-gradient-to-br from-red-200 to-orange-300', 'bg-gradient-to-br from-gray-200 to-slate-300', 'bg-gradient-to-br from-stone-200 to-zinc-300', 'bg-gradient-to-br from-amber-200 to-yellow-300'],
    items: [{ rank: 1, albumId: 'her', votes: 76 }, { rank: 2, albumId: '23', votes: 68 }, { rank: 3, albumId: 'realists', votes: 58 }, { rank: 4, albumId: 'so-nyeon-i-onda', votes: 48 }, { rank: 5, albumId: 'still-life', votes: 42 }],
  },
  {
    id: 'usa-alternative',
    title: 'Best American Alternative Albums',
    country: 'USA',
    genre: 'Alternative',
    votes: 678,
    coverGradients: ['bg-gradient-to-br from-slate-300 to-gray-400', 'bg-gradient-to-br from-teal-200 to-cyan-300', 'bg-gradient-to-br from-indigo-200 to-violet-300', 'bg-gradient-to-br from-gray-200 to-stone-300'],
    items: [{ rank: 1, albumId: 'night-swimming', votes: 72 }, { rank: 2, albumId: 'broken-mirror', votes: 64 }, { rank: 3, albumId: 'her', votes: 56 }, { rank: 4, albumId: 'so-nyeon-i-onda', votes: 48 }, { rank: 5, albumId: 'realists', votes: 42 }],
  },
  {
    id: 'usa-folk',
    title: 'Best American Folk Albums',
    country: 'USA',
    genre: 'Folk',
    votes: 432,
    coverGradients: ['bg-gradient-to-br from-amber-200 to-yellow-300', 'bg-gradient-to-br from-green-200 to-emerald-300', 'bg-gradient-to-br from-orange-200 to-lime-300', 'bg-gradient-to-br from-stone-200 to-zinc-300'],
    items: [{ rank: 1, albumId: 'seonmul', votes: 48 }, { rank: 2, albumId: 'japcho', votes: 42 }, { rank: 3, albumId: 'aaa', votes: 36 }, { rank: 4, albumId: 'modern-times', votes: 30 }, { rank: 5, albumId: 'chat-shire', votes: 26 }],
  },

  // ── UK ──
  {
    id: 'uk-pop',
    title: 'Best UK Pop Albums',
    country: 'UK',
    genre: 'Pop',
    votes: 756,
    coverGradients: ['bg-gradient-to-br from-pink-200 to-rose-300', 'bg-gradient-to-br from-teal-200 to-emerald-300', 'bg-gradient-to-br from-violet-200 to-purple-300', 'bg-gradient-to-br from-sky-200 to-cyan-300'],
    items: [{ rank: 1, albumId: 'palette', votes: 68 }, { rank: 2, albumId: 'the-album', votes: 58 }, { rank: 3, albumId: 'lilac', votes: 52 }, { rank: 4, albumId: 'queendom', votes: 44 }, { rank: 5, albumId: 'omg', votes: 38 }],
  },
  {
    id: 'uk-rock',
    title: 'Best UK Rock Albums',
    country: 'UK',
    genre: 'Rock',
    votes: 892,
    coverGradients: ['bg-gradient-to-br from-red-200 to-orange-300', 'bg-gradient-to-br from-gray-200 to-slate-300', 'bg-gradient-to-br from-stone-200 to-zinc-300', 'bg-gradient-to-br from-amber-200 to-yellow-300'],
    items: [{ rank: 1, albumId: 'her', votes: 82 }, { rank: 2, albumId: '23', votes: 74 }, { rank: 3, albumId: 'realists', votes: 64 }, { rank: 4, albumId: 'so-nyeon-i-onda', votes: 56 }, { rank: 5, albumId: 'still-life', votes: 48 }],
  },
  {
    id: 'uk-alternative',
    title: 'Best UK Alternative Albums',
    country: 'UK',
    genre: 'Alternative',
    votes: 612,
    coverGradients: ['bg-gradient-to-br from-slate-300 to-gray-400', 'bg-gradient-to-br from-teal-200 to-cyan-300', 'bg-gradient-to-br from-indigo-200 to-violet-300', 'bg-gradient-to-br from-gray-200 to-stone-300'],
    items: [{ rank: 1, albumId: 'night-swimming', votes: 68 }, { rank: 2, albumId: 'broken-mirror', votes: 58 }, { rank: 3, albumId: 'her', votes: 52 }, { rank: 4, albumId: 'so-nyeon-i-onda', votes: 44 }, { rank: 5, albumId: 'realists', votes: 38 }],
  },
  {
    id: 'uk-indie-rock',
    title: 'Best UK Indie Rock Albums',
    country: 'UK',
    genre: 'Indie Rock',
    votes: 534,
    coverGradients: ['bg-gradient-to-br from-red-200 to-rose-300', 'bg-gradient-to-br from-orange-200 to-amber-300', 'bg-gradient-to-br from-teal-200 to-emerald-300', 'bg-gradient-to-br from-gray-200 to-slate-300'],
    items: [{ rank: 1, albumId: 'her', votes: 68 }, { rank: 2, albumId: '23', votes: 60 }, { rank: 3, albumId: 'realists', votes: 52 }, { rank: 4, albumId: 'so-nyeon-i-onda', votes: 44 }, { rank: 5, albumId: 'broken-mirror', votes: 38 }],
  },
  {
    id: 'uk-shoegaze',
    title: 'Best UK Shoegaze Albums',
    country: 'UK',
    genre: 'Shoegaze',
    votes: 378,
    coverGradients: ['bg-gradient-to-br from-slate-300 to-gray-400', 'bg-gradient-to-br from-blue-200 to-indigo-300', 'bg-gradient-to-br from-violet-200 to-purple-300', 'bg-gradient-to-br from-cyan-200 to-teal-300'],
    items: [{ rank: 1, albumId: 'night-swimming', votes: 52 }, { rank: 2, albumId: 'her', votes: 46 }, { rank: 3, albumId: '23', votes: 40 }, { rank: 4, albumId: 'realists', votes: 34 }, { rank: 5, albumId: 'so-nyeon-i-onda', votes: 28 }],
  },

  // ── Philippines ──
  {
    id: 'ph-ppop',
    title: 'Best P-Pop Albums',
    country: 'Philippines',
    genre: 'P-Pop',
    votes: 432,
    coverGradients: ['bg-gradient-to-br from-pink-200 to-rose-300', 'bg-gradient-to-br from-teal-200 to-emerald-300', 'bg-gradient-to-br from-amber-200 to-yellow-300', 'bg-gradient-to-br from-violet-200 to-purple-300'],
    items: [{ rank: 1, albumId: 'palette', votes: 42 }, { rank: 2, albumId: 'the-album', votes: 38 }, { rank: 3, albumId: 'omg', votes: 32 }, { rank: 4, albumId: 'queendom', votes: 28 }, { rank: 5, albumId: 'antifragile', votes: 24 }],
  },
  {
    id: 'ph-opm',
    title: 'Best OPM Albums',
    country: 'Philippines',
    genre: 'OPM',
    votes: 356,
    coverGradients: ['bg-gradient-to-br from-amber-200 to-orange-300', 'bg-gradient-to-br from-sky-200 to-cyan-300', 'bg-gradient-to-br from-pink-200 to-rose-300', 'bg-gradient-to-br from-green-200 to-emerald-300'],
    items: [{ rank: 1, albumId: 'seonmul', votes: 36 }, { rank: 2, albumId: 'the-shower', votes: 32 }, { rank: 3, albumId: 'last-fantasy', votes: 28 }, { rank: 4, albumId: 'japcho', votes: 24 }, { rank: 5, albumId: 'modern-times', votes: 20 }],
  },

  // ── Indonesia ──
  {
    id: 'id-indo-pop',
    title: 'Best Indo Pop Albums',
    country: 'Indonesia',
    genre: 'Indo Pop',
    votes: 298,
    coverGradients: ['bg-gradient-to-br from-teal-200 to-emerald-300', 'bg-gradient-to-br from-amber-200 to-yellow-300', 'bg-gradient-to-br from-pink-200 to-rose-300', 'bg-gradient-to-br from-orange-200 to-amber-300'],
    items: [{ rank: 1, albumId: 'palette', votes: 28 }, { rank: 2, albumId: 'lilac', votes: 24 }, { rank: 3, albumId: 'chat-shire', votes: 22 }, { rank: 4, albumId: 'modern-times', votes: 18 }, { rank: 5, albumId: 'real', votes: 16 }],
  },
  {
    id: 'id-dangdut',
    title: 'Best Dangdut Albums',
    country: 'Indonesia',
    genre: 'Dangdut',
    votes: 156,
    coverGradients: ['bg-gradient-to-br from-yellow-200 to-lime-300', 'bg-gradient-to-br from-orange-200 to-red-300', 'bg-gradient-to-br from-amber-200 to-yellow-300', 'bg-gradient-to-br from-green-200 to-emerald-300'],
    items: [{ rank: 1, albumId: 'seonmul', votes: 18 }, { rank: 2, albumId: 'japcho', votes: 16 }, { rank: 3, albumId: 'the-shower', votes: 14 }, { rank: 4, albumId: 'last-fantasy', votes: 12 }, { rank: 5, albumId: 'modern-times', votes: 10 }],
  },

  // ── Thailand ──
  {
    id: 'th-tpop',
    title: 'Best T-Pop Albums',
    country: 'Thailand',
    genre: 'T-Pop',
    votes: 312,
    coverGradients: ['bg-gradient-to-br from-pink-200 to-rose-300', 'bg-gradient-to-br from-teal-200 to-cyan-300', 'bg-gradient-to-br from-violet-200 to-purple-300', 'bg-gradient-to-br from-amber-200 to-yellow-300'],
    items: [{ rank: 1, albumId: 'palette', votes: 32 }, { rank: 2, albumId: 'the-album', votes: 28 }, { rank: 3, albumId: 'lilac', votes: 24 }, { rank: 4, albumId: 'queendom', votes: 20 }, { rank: 5, albumId: 'omg', votes: 18 }],
  },

  // ── Vietnam ──
  {
    id: 'vn-vpop',
    title: 'Best V-Pop Albums',
    country: 'Vietnam',
    genre: 'V-Pop',
    votes: 276,
    coverGradients: ['bg-gradient-to-br from-rose-200 to-pink-300', 'bg-gradient-to-br from-sky-200 to-cyan-300', 'bg-gradient-to-br from-amber-200 to-orange-300', 'bg-gradient-to-br from-emerald-200 to-green-300'],
    items: [{ rank: 1, albumId: 'palette', votes: 28 }, { rank: 2, albumId: 'lilac', votes: 24 }, { rank: 3, albumId: 'chat-shire', votes: 20 }, { rank: 4, albumId: 'modern-times', votes: 18 }, { rank: 5, albumId: 'real', votes: 16 }],
  },

  // ── China ──
  {
    id: 'cn-cpop',
    title: 'Best C-Pop Albums',
    country: 'China',
    genre: 'C-Pop',
    votes: 876,
    coverGradients: ['bg-gradient-to-br from-red-200 to-rose-300', 'bg-gradient-to-br from-amber-200 to-yellow-300', 'bg-gradient-to-br from-pink-200 to-fuchsia-300', 'bg-gradient-to-br from-teal-200 to-emerald-300'],
    items: [{ rank: 1, albumId: 'palette', votes: 72 }, { rank: 2, albumId: 'the-album', votes: 64 }, { rank: 3, albumId: 'lilac', votes: 56 }, { rank: 4, albumId: 'queendom', votes: 48 }, { rank: 5, albumId: 'map-of-the-soul', votes: 42 }],
  },
  {
    id: 'cn-mandopop',
    title: 'Best Mandopop Albums',
    country: 'China',
    genre: 'Mandopop',
    votes: 654,
    coverGradients: ['bg-gradient-to-br from-sky-200 to-cyan-300', 'bg-gradient-to-br from-pink-200 to-rose-300', 'bg-gradient-to-br from-violet-200 to-purple-300', 'bg-gradient-to-br from-amber-200 to-orange-300'],
    items: [{ rank: 1, albumId: 'palette', votes: 58 }, { rank: 2, albumId: 'seonmul', votes: 52 }, { rank: 3, albumId: 'modern-times', votes: 46 }, { rank: 4, albumId: 'lilac', votes: 40 }, { rank: 5, albumId: 'the-shower', votes: 34 }],
  },
  {
    id: 'cn-cantopop',
    title: 'Best Cantopop Albums',
    country: 'China',
    genre: 'Cantopop',
    votes: 432,
    coverGradients: ['bg-gradient-to-br from-blue-200 to-indigo-300', 'bg-gradient-to-br from-rose-200 to-pink-300', 'bg-gradient-to-br from-amber-200 to-yellow-300', 'bg-gradient-to-br from-teal-200 to-emerald-300'],
    items: [{ rank: 1, albumId: 'seonmul', votes: 42 }, { rank: 2, albumId: 'the-shower', votes: 38 }, { rank: 3, albumId: 'last-fantasy', votes: 34 }, { rank: 4, albumId: 'modern-times', votes: 28 }, { rank: 5, albumId: 'real', votes: 24 }],
  },
];

export const curatedLists: CuratedList[] = [
  {
    id: 'essential-k-indie',
    title: 'Essential K-Indie',
    description: 'The records that define Korean independent music, curated from across the decade.',
    author: 'kenneth',
    authorInitial: 'K',
    albumCount: 12,
    createdAt: '3d ago',
    albumIds: ['broken-mirror', 'her', 'night-swimming', 'bleu', '23', 'seonmul', 'so-nyeon-i-onda', 'realists'],
  },
];

export function getAlbumById(id: string): Album | undefined {
  return albums.find(a => a.id === id);
}

export function getArtistById(id: string): Artist | undefined {
  return artists.find(a => a.id === id);
}

export function getAlbumsByArtist(artistId: string): Album[] {
  return albums.filter(a => a.artistId === artistId).sort((a, b) => b.year - a.year);
}

export function getAlbumsByGenre(genre: string): Album[] {
  return albums.filter(a => a.genres.includes(genre)).sort((a, b) => b.year - a.year);
}

export function getReviewsForAlbum(albumId: string): Review[] {
  return reviews.filter(r => r.albumId === albumId);
}

export function getArtistDiscography(artistId: string): Album[] {
  return albums.filter(a => a.artistId === artistId);
}

export const recentRatings = [
  { albumId: 'midsummer-night', rating: 4.5 },
  { albumId: 'get-up', rating: 3.5 },
  { albumId: 'broken-mirror', rating: 5.0 },
  { albumId: 'palette', rating: 4.0 },
  { albumId: 'love-yourself', rating: 4.0 },
  { albumId: 'seven-seasons', rating: 3.0 },
];

export const becauseYouLiked = [
  'society', '24hours', 'gravity', 'everything', 'still-life', 'when', 'daydream', 'bliss',
];

export const genreRows = [
  {
    genre: 'K-Pop',
    description: 'Korean pop — idol groups and solo artists',
    albumIds: ['omg', 'the-album', 'map-of-the-soul', 'noeasy', 'pink-venom', 'proof', 'antifragile', 'queendom'],
  },
  {
    genre: 'K-Indie',
    description: 'Independent Korean artists — raw and personal',
    albumIds: ['her', '23', 'seonmul', 'japcho', 'night-swimming', 'aaa'],
  },
  {
    genre: 'K-R&B',
    description: 'Korean R&B and neo-soul',
    albumIds: ['bleu', '180', '24', '202', 'summer-love', 'grown'],
  },
  {
    genre: 'City Pop & J-Pop',
    description: 'Japanese pop and city pop classics',
    albumIds: ['plastic-love', 'pacific', 'surf-rain', 'for-you', 'niagara-triangle'],
  },
];

export const forYouAlbumIds = [
  'broken-mirror', 'her', 'palette', 'night-swimming', 'omg', 'chat-shire', 'bleu', 'lilac', '23', 'modern-times', 'seonmul', 'realists',
];

export const pinnedTenIds = [
  'midsummer-night', 'lilac', 'palette', 'broken-mirror', 'chat-shire', 'modern-times', 'the-shower', null, null,
];

export const profileStats = {
  ratings: 247,
  reviews: 38,
  following: 12,
  followers: 31,
  avgScore: 3.8,
  distribution: [10, 18, 28, 36, 48, 56, 60, 72, 64, 44],
  topGenres: [
    { name: 'K-R&B', count: 64 },
    { name: 'K-Indie', count: 48 },
    { name: 'Hip-Hop', count: 38 },
    { name: 'K-Pop', count: 31 },
    { name: 'R&B', count: 22 },
  ],
  insights: [
    "Your ratings land close to the community average",
    "Perfect scores are rare for you — only 6 given",
    "You're not afraid to rate low — 26% are 2★ or below",
  ],
};

export const wrappedStats = {
  albumsRated: 47,
  avgScore: 3.8,
  perfectScores: 6,
  perfectPercentage: 13,
  topGenre: 'K-Indie',
  mostRatedArtist: 'IU',
  mostRatedArtistCount: 5,
  mostActiveMonth: 'March',
  mostActiveMonthCount: 11,
  highestRated: { albumId: 'broken-mirror', rating: 5.0 },
  lowestRated: { albumId: 'face', rating: 1.5 },
};
