import SwiftUI

// sjCream, sjInk, sjMuted, sjBorder, sjSurface are defined as color assets
// in Assets.xcassets and auto-generated by Xcode — no manual declarations needed.

extension Color {
    static let sjAmber        = Color(red: 0.910, green: 0.627, blue: 0.125) // #E8A020
    static let sjSpotifyGreen = Color(red: 0.114, green: 0.722, blue: 0.333) // #1DB954
}
