import SwiftUI

// sjCream, sjInk, sjMuted, sjBorder, sjSurface are defined as color assets
// in Assets.xcassets and auto-generated by Xcode — no manual declarations needed.

extension Color {
    static let sjBlue         = Color(red: 0.161, green: 0.475, blue: 0.718) // #2979B7
    static let sjAmber        = sjBlue   // alias — theme color is now blue
    static let sjSpotifyGreen = Color(red: 0.114, green: 0.722, blue: 0.333) // #1DB954
}
